### ISSUE TITLE
Question about the init temporal model

### ISSUE THREAD

**Issue by whwu95** [bryanyzhu/Hidden-Two-Stream#1]
In this paper, you said "the temporal model is initialized with the snapshot provided by Wang",could you give me the snapshot URL?
Thank you.

**Comment by bryanyzhu** [comment]
Sure, here it is. 

https://github.com/yjxiong/caffe/tree/action_recog/models/action_recognition

**Comment by whwu95** [comment]
you mean it is http://mmlab.siat.ac.cn/pretrain/vgg_16_action_flow_pretrain.caffemodel  or http://mmlab.siat.ac.cn/very_deep_two_stream_model/cuhk_action_temporal_vgg_16_split1.caffemodel ?

**Comment by bryanyzhu** [comment]
oh, i mean the second url.

But i also try the first url as init model. It just take longer time (around 8K iter) to reach the same performance.

**Comment by cherishtttz** [comment]
hello, when I  compiled the code and I followed the 'README' to make under Ubuntu16.04, I can't compile it successfully, the mistake is 'recipe for target '.build_release/tools/convert_imageset_and_disparity.o failed', I don't know how to solve this problem, have you ever met that question? Please help me ,thanks so much!

**Comment by bryanyzhu** [comment]
Hi, I think the problem is related to this file [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/tools/convert_imageset_and_disparity.cpp). You can follow the error messages to debug. If there is no detailed error message, I think you can also delete this cpp file from the `tools` directory. It shouldn't effect our functionality. The cpp file is made for original FlowNet and DispNet paper.
