### ISSUE TITLE
Timeout Error while Testing

### ISSUE THREAD

**Issue by EileenSchreiber** [bryanyzhu/Hidden-Two-Stream#11]
System:
CUDA 8.0
CuDNN 5.1
GPU Nvidia 1060 6GB

The training process worked fine, so I wanted to test it according to your description, but I get the following error:
```
I0323 16:50:23.343171 19562 net.cpp:753] Ignoring source layer action_loss
we got 3783 test videos
1
F0323 16:50:33.064666 19562 math_functions.cu:79] Check failed: error == cudaSuccess (6 vs. 0)  the launch timed out and was terminated
*** Check failure stack trace: ***
Aborted
```

I printed the 1 to see where it seems to stop, which is in file Hidden-Two-Stream/models/ucf101_split1_unsup_end/eval_ucf101/HiddenTemporalPrediction.py:

    for bb in range(num_batches):
        span = range(batch_size*bb, min(rgb.shape[3],batch_size*(bb+1)))
        net.blobs['data'].data[...] = np.transpose(rgb[:,:,:,span], (3,2,1,0))
        print 1
        output = net.forward()
        print 2
        prediction[:, span] = np.transpose(output[feature_layer])

The error message shows that the error gets thrown in Hidden-Two-Stream/src/caffe/util/math_functions.cu: 

```
void caffe_gpu_memcpy(const size_t N, const void* X, void* Y) {
  if (X != Y) {
    CUDA_CHECK(cudaMemcpy(Y, X, N, cudaMemcpyDefault));  // NOLINT(caffe/alt_fn)
  }
}
```

The problem is I cant seem to find the connection from `net.forward()` to `caffe_gpu_memcpy` and where it gets called. Can you help me solve this error and tell me where `caffe_gpu_memcpy` is called? 

Thank you in advance.

**Comment by bryanyzhu** [comment]
Hi, thanks for trying out the code. I think maybe the problem is your GPU memory is small, so you encounter the out of memory error. Try reduce the batch size during test. 

Specifically, reduce batch_size [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/eval_ucf101/HiddenTemporalPrediction.py#L69) and [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/stack_motionnet_vgg16_deploy.prototxt#L3). Since for each video, we will have 250 frames in total (25 sampled frames, and 10-crop augmentation, so 25 x 10 = 250). Your batch size should be multiples of 5. I suggest try 25 first. If doesn't work, try 10 or even 5. But be warned that the test time will be much longer due to small batch size.

**Comment by EileenSchreiber** [comment]
Hi, thanks for your advice. 
However, the same error still occurs even though I reduced the `batch_size` to 1. 
Do you have an idea where `caffe_gpu_memcpy` is called or what else could cause the problem?

**Comment by bryanyzhu** [comment]
Hi, I am sorry I don't have such experience. Usually most people encounter cudasuccess 2 vs 0, which is the out of memory error. I searched online for your problem at [here](https://github.com/fireice-uk/xmr-stak-nvidia/issues/40), [here](https://devtalk.nvidia.com/default/topic/483643/cuda-the-launch-timed-out-and-was-terminated/) and [here](https://stackoverflow.com/questions/6185117/cudamemcpy-errorthe-launch-timed-out-and-was-terminated). I don't quite understand their answers, but it seems that the computation is too much for your card (or the threads management is out of order). But I think 1060 is a pretty decent card, it shouldn't happen such problems. 

Are you using multiple cards? And can you reduce the size of the network and try again? I mean, you only use 2 layers for motionnet, and 2 layers for temporal stream. You don't need to train the model long, you just get such a model and test it. If the evaluation script goes well, then it means it is the computation load is too much. Otherwise, we can focus on something else.

**Comment by EileenSchreiber** [comment]
Hi, thanks for all your help again. 
Today I tried it on another pc with a GeForce GTX 960 with 2GB and its seems to be working. I have no idea why it didn't work before. However, I am happy as long as it is working now :)

**Comment by bryanyzhu** [comment]
Great to hear it is working now, cheers.

**Comment by adimurthi** [comment]
Hi,
    As a part of my thesis I am implementing this project. sadly i am new to this technology i am getting errors during training. could you please share detailed implementation steps with me. thank you
