### ISSUE TITLE
About Flow loss

### ISSUE THREAD

**Issue by adimurthi** [bryanyzhu/Hidden-Two-Stream#28]
Hi Sir, 
           could you please explain unsupervised loss, In paper, motion information calculated using two frames and reconstruct flow image using predicted flow and frame2.  Here, I understood that 'Img10Norm" is frame 1 and "predict_flow_6_0" is frame 2 , "downsampled_img10_6" is predicted filed. is that correct? I did not understand how image is reconstructed from "downsampled_img10_6"
 `layer {
  name: "WarpDownsample6_10"
  type: "Downsample"
  bottom: "img10Norm"
  bottom: "predict_flow6_0"
  top: "downsampled_img10_6"
  propagate_down: false 
  propagate_down: false 
}

# warp frame 2 back to frame 1
layer{
  name: "FlowScale6_0"
  type: "Scale"
  bottom: "predict_flow6_0"
  top: "FlowScale6_0"
  scale_param {
    filler {
      type: "constant"
      value: 0.625
    }
    bias_term : false
  }
  param { 
    lr_mult: 0 
  }
}`

**Comment by bryanyzhu** [comment]
Hi, 

```
`layer {
name: "WarpDownsample6_10"
type: "Downsample"
bottom: "img10Norm"
bottom: "predict_flow6_0"
top: "downsampled_img10_6"
propagate_down: false
propagate_down: false
}
```
This part is only for downsampling. `img10Norm` is the normalized image at original size, `downsampled_img10_6` is the downsampled image. They are the same image, just size is different. `predict_flow6_0` here only provide the size information. Because we want to know how much we need to downsample the image. There is no warping involved here. 


```
layer{
name: "FlowScale6_0"
type: "Scale"
bottom: "predict_flow6_0"
top: "FlowScale6_0"
scale_param {
filler {
type: "constant"
value: 0.625
}
bias_term : false
}
param {
lr_mult: 0
}
}`
```
For this part, it is for scaling the flow. Because for image at different sizes, we need to enlarge or decrease the magnitude of flow vectors before we perform warping. For example, if you have an image of 200x200 and a car moves 20 pixels, then the flow is 20. But if you downsample the image to 100x100, you need to divide your flow vector by 2 as well. Otherwise, the car will move too fast, which is wrong. There is no warping involved here. 

```
layer{
  name: "Warp6_9"
  type: "FlowTransformer"
  bottom: "downsampled_img10_6"
  bottom: "FlowScale6_9"
  top: "Warped6_9"
}
```

For this part, this is the actual warping. `downsampled_img10_6` is the downsampled image, `FlowScale6_9` is the magnitude-reduced flow, and the output `Warped6_9` is the reconstructed image. Hope this is clear.

**Comment by adimurthi** [comment]
Hi,
      you made it very clear, thank you so much..
