### ISSUE TITLE
spatial model

### ISSUE THREAD

**Issue by minhnova** [bryanyzhu/Hidden-Two-Stream#32]
Dear Bryan Zhu,

Could you please give me the link to the VGG16 spatial model (which is pre-trained on ImageNet and trained on UCF-101)? 
I followed your paper and download a model name: cuhk_action_spatial_vgg_16_split1.caffemodel from this link "https://github.com/yjxiong/caffe/tree/action_recog/models/action_recognition" but I got very low accuracy ( around 53.4%).

Thank you so much,
Best,

**Comment by NicoleNicoleXiang** [comment]
Dear Bryan Zhu,

when i was trying to generate training and test list by running bash scripts/build_file_list.sh ucf101 FRAME_PATH
i got this error:
Traceback (most recent call last):
File "tools/build_file_list.py", line 39, in 
lists = build_split_list(split_tp, f_info, i, shuffle)
File "/home/xlp/project4/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 64, in build_split_list
train_rgb_list, train_flow_list = build_set_list(split[0])
File "/home/xlp/project4/temporal-segment-networks/pyActionRecog/benchmark_db.py", line 54, in build_set_list
frame_dir = frame_info[0][item[0]]
KeyError: 'v_ApplyEyeMakeup_g08_c01'

**Comment by bryanyzhu** [comment]
Hi for your first question, I used the same model as you did. There are two things that may need additional attention. (1) How do you do the evaluation? Did you do 10-crop, flipping, random sampling of 25 frames from a video? Because those are standard technique during inference. (2) If you do the correct evaluation, then it may be your data problem. The image quality may be quite bad. You need to re-extract your video frames. 

For your second question, that is the code from TSN repo, right? I think many people use that, the code should be correct. It is just your setting may be wrong. You can try the code in my repo at [here](https://github.com/bryanyzhu/two-stream-pytorch), follow the readme. If you still encounter problems, let me know.

**Comment by minhnova** [comment]
Thank you so much for your answer. 
I used the same code with your file HiddenTemporalPrediction.py to run the evaluation. 
The spatial model 53.4% accuracy and the temporal model I got 73% accuracy. In the file "HiddenTemporalPrediction"  you did "10-crop, flipping, random sampling of 25 frames" right?

Thank you a lot for your help.

Best,
