### ISSUE TITLE
I want to ask a question about training and test networks

### ISSUE THREAD

**Issue by Tylerjoe** [bryanyzhu/Hidden-Two-Stream#33]
@bryanyzhu 
I want to ask question, why the networks are different between trainning and test?
you use end_train_val.prototxt for training , but you use stack_motionnet_vgg16_deploy.prototxt

Thanks!

**Comment by bryanyzhu** [comment]
Hi, `end_train_val.prototxt` and `stack_motionnet_vgg16_deploy.prototxt` are not that different. `end_train_val.prototxt` has all the loss computation. I removed those layers because they are not needed during test. Hope this is clear. 

Other than loss computation, the other layers should be exactly the same in both files.

**Comment by Tylerjoe** [comment]
@bryanyzhu it's very clear. Thank you very much
