### ISSUE TITLE
about the supervised and  unsupervised learning MotionNet

### ISSUE THREAD

**Issue by niujiaopeng** [bryanyzhu/Hidden-Two-Stream#34]
thank you for your job.
here is my question: In your another paper:"Guided Optical Flow Learning" ,you compare the supervised and unsupervised  when learning optical flow, in that paper you  first do supervised learning and then unsupervised learning, and only unsupervised learning EPE is worse;  so why in this paper only use the unsupervised learning?

**Comment by bryanyzhu** [comment]
Hi, I want to answer your question in several aspects. 

First, even we can get better performance from supervised learning for now, my goal of learning optical flow is always `unsupervised learning` because it is hard for us to get ground truth. Unsupervised learning of optical flow is a more appealing research topic to me. 

Second, in "Guided Optical Flow Learning", it is actually a `unsupervised learning` regime, because I didn't use ground truth. I use flow estimates from other methods to be the pseudo ground truth. Hence, actually I am still doing unsupervised learning. I just want to show that by pseud ground truth guidance, we can achieve similar performance compared to using the real ground truth. In this way, we can get refined optical flow in many domains without ground truth. For example, problems like action recognition and autonomous driving, we can learn flow on the target domain instead of using fixed flow estimator like FlowNet2. 

Third, this is research paper writing, not a competition. In a competition, you want to use every good practice you know to get the best score. For example, if  you know supervised is better, then you won't use unsupervised. But here, I am exploring possible techniques to improve unsupervised learning of optical flow. I don't care about the best performance, as long as I improve over previous best unsupervised methods. 

Hope this helps.
