### ISSUE TITLE
model for motionnet restricts the flow size

### ISSUE THREAD

**Issue by Zealoe** [bryanyzhu/Hidden-Two-Stream#9]
Sorry to bother, but i have trouble with motionnet, because the flow is restricted by the network, so if i resize the flow using numpy, the flow will be wrong. So what should i do if i want to get flow which is the same size as the original images? thanks!

**Comment by Zealoe** [comment]
also, wanna ask how to change the input size? Because the output flow is too small. I want to make it larger. Thanks

**Comment by bryanyzhu** [comment]
Hi, since motionnet is fully convolutional network. So you can feed images with any size, and it will give you the larger size flow output. Just change the height and width params [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/multiframe_MotionNet/scripts/generate_flow_for_ucf101.py#L47-L49). And also remember to change the params [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/multiframe_MotionNet/deploy.prototxt#L3-L6) in the deploy.prototxt. You are good to go.
